#!/usr/bin/env python3
"""
Pick the best strategy per pair based on walk-forward backtest results.
Writes winner to config/chosen_strategies.json.

Usage:
  python scripts/pick_strategy.py
  python scripts/pick_strategy.py --symbol BTCUSDT
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bot import config
from bot.backtester import BacktestMetrics, print_leaderboard, run_backtest
from bot.data import load_candles
from bot.strategies.mean_reversion import MeanReversionStrategy
from bot.strategies.trend_ema import TrendEMAStrategy
from bot.strategies.breakout_donchian import BreakoutDonchianStrategy
from bot.strategies.momentum_macd import MomentumMACDStrategy

STRATEGIES = [
    MeanReversionStrategy(),
    TrendEMAStrategy(),
    BreakoutDonchianStrategy(),
    MomentumMACDStrategy(),
]

# Composite score weights — profit-first, then consistency, then drawdown penalty
SCORE_WEIGHTS = {
    "net_pnl_usdt":     0.40,
    "profit_factor":    0.30,
    "win_rate":         0.20,
    "max_drawdown_pct": -0.10,  # penalise; lower is better
}

# Minimum trade count to consider a backtest result valid
MIN_TRADES = 3


def composite_score(m: BacktestMetrics) -> float:
    """Composite ranking score. Returns -inf for insufficient trade count."""
    if m.total_trades < MIN_TRADES:
        return float("-inf")
    pf = min(m.profit_factor, 10.0)  # cap inf profit_factor to avoid distortion
    return (
        m.net_pnl_usdt     * SCORE_WEIGHTS["net_pnl_usdt"]
        + pf               * SCORE_WEIGHTS["profit_factor"]
        + m.win_rate       * SCORE_WEIGHTS["win_rate"]
        + m.max_drawdown_pct * SCORE_WEIGHTS["max_drawdown_pct"]
    )


def _run_for_symbols(
    symbols: list,
    min_confidence: float = 0.0,
    save: bool = True,
) -> list:
    """Run backtest for given symbols and return list of BacktestMetrics."""
    all_metrics: list[BacktestMetrics] = []
    chosen: dict[str, str] = {}
    missing: list[str] = []

    label = f"min_confidence={min_confidence:.1f}" if min_confidence > 0 else "baseline (no filter)"
    print(f"\nRunning backtest [{label}]: {len(symbols)} pair(s) × {len(STRATEGIES)} strategies\n")

    for symbol in symbols:
        candles = load_candles(symbol)
        if not candles:
            print(f"  [{symbol}] No cache — run: python scripts/fetch_history.py")
            missing.append(symbol)
            continue

        print(f"  [{symbol}] {len(candles):,} candles — running strategies ...", end="", flush=True)
        pair_results: list[BacktestMetrics] = []
        for strategy in STRATEGIES:
            m = run_backtest(strategy, candles, symbol=symbol, min_confidence=min_confidence)
            pair_results.append(m)
            all_metrics.append(m)
        print(f" done ({sum(m.total_trades for m in pair_results)} total trades across strategies)")

        best = max(pair_results, key=composite_score)
        best_score = composite_score(best)

        if best_score == float("-inf"):
            best = max(pair_results, key=lambda m: m.total_trades)
            print(f"  [{symbol}] ⚠ Low trade count — defaulting to: {best.strategy_name}")
        else:
            print(f"  [{symbol}] ✔ Winner: {best.strategy_name}  "
                  f"(score={best_score:.4f}, trades={best.total_trades}, "
                  f"pnl={best.net_pnl_usdt:+.4f}, win={best.win_rate:.0%})")
        chosen[symbol] = best.strategy_name

    print()
    if all_metrics:
        print_leaderboard(all_metrics)

    if save and chosen:
        existing = config.load_chosen_strategies()
        existing.pop("_note", None)
        merged = {**existing, **chosen}
        merged["_note"] = (
            f"Auto-generated by pick_strategy.py — "
            f"min_confidence={min_confidence:.1f}. Do not edit manually."
        )
        ordered = {"_note": merged.pop("_note"), **merged}
        config.save_chosen_strategies(ordered)
        print(f"\n✔ Saved → {config.CHOSEN_STRATEGIES_FILE}")

    return all_metrics


def _run_comparison(symbol_arg) -> int:
    """Run baseline vs filtered and print a delta table."""
    symbols = [symbol_arg] if symbol_arg else config.PAIRS
    print("\n═" * 40)
    print("COMPARISON: baseline (no filter) vs confidence≥0.3 + profit gate")
    print("═" * 40)

    base = _run_for_symbols(symbols, min_confidence=0.0, save=False)
    filt = _run_for_symbols(symbols, min_confidence=0.3, save=True)  # save the filtered version

    # Build lookup
    base_map = {(m.symbol, m.strategy_name): m for m in base}
    filt_map = {(m.symbol, m.strategy_name): m for m in filt}

    print("\n── Delta table (filtered − baseline) ────────────────────────────")
    header = f"{'Symbol':<10}  {'Strategy':<22}  {'Base Trades':>11}  {'Filt Trades':>11}  {'BasePnL':>8}  {'FiltPnL':>8}  {'ΔPnL':>8}"
    print("-" * len(header))
    print(header)
    print("-" * len(header))

    keys = sorted(base_map.keys())
    for key in keys:
        b = base_map[key]
        f = filt_map.get(key)
        if f is None:
            continue
        delta = f.net_pnl_usdt - b.net_pnl_usdt
        print(
            f"{b.symbol:<10}  {b.strategy_name:<22}  "
            f"{b.total_trades:>11}  {f.total_trades:>11}  "
            f"{b.net_pnl_usdt:>+8.4f}  {f.net_pnl_usdt:>+8.4f}  {delta:>+8.4f}"
        )
    print("-" * len(header))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Pick best strategy per pair via backtest")
    parser.add_argument("--symbol", default=None, help="Single symbol (default: all pairs)")
    parser.add_argument(
        "--min-confidence", type=float, default=0.0,
        help="Skip signals below this confidence (0.0=off, 0.3=recommended filter)",
    )
    parser.add_argument(
        "--compare", action="store_true",
        help="Run baseline vs filtered comparison side-by-side (ignores --min-confidence)",
    )
    args = parser.parse_args()

    if args.compare:
        return _run_comparison(args.symbol)

    symbols = [args.symbol] if args.symbol else config.PAIRS
    _run_for_symbols(symbols, min_confidence=args.min_confidence, save=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
